spring.application.name=userLoginSpringSecurity

#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/user_login
spring.datasource.username=postgres
spring.datasource.password=1805
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


api.security.token.secret=my-secret