spring.application.name=userLoginSpringSecurity

#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/nomedobanco
spring.datasource.username=seuUsuario
spring.datasource.password=suaSenha
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
